apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment
  labels:
    app: db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:

      - name: mysql
        image: kondareddy45/gaming-db:v1

        ports:
        - containerPort: 3306

        env:

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-gameing
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: MYSQL_DATABASE

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets-gameing
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-gameing
              key: MYSQL_PASSWORD
---                
apiVersion: v1
kind: Service
metadata: 
  name: db-svc
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
