apiVersion: v1
kind: Secret

metadata:
  name: secrets-gameing

type: Opaque

data:

  MYSQL_ROOT_PASSWORD: cm9vdEAxMjM=

  MYSQL_USER: Z2FtZXVzZXI=

  MYSQL_PASSWORD: Z2FtZUAxMjM=

  DB_USER: Z2FtZXVzZXI=
  DB_PASSWORD: Z2FtZUAxMjM=
