apiVersion: apps/v1
kind: Deployment

metadata:
  name: db-deployment
  labels:
    app: db

spec:
  replicas: 1   # DB usually runs single replica

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:

      - name: mysql

        image: kondareddy45/node-js-db:v1

        ports:
        - containerPort: 3306

        env:

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

---
apiVersion: v1
kind: Service
metadata: 
  name: db-svc
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
