apiVersion: apps/v1
kind: StatefulSet

metadata:
 name: mysql

spec:

 serviceName: mysql-svc

 replicas: 1

 selector:
  matchLabels:
   app: mysql

 template:

  metadata:
   labels:
    app: mysql

  spec:

   containers:

   - name: mysql

     image: mysql:8

     env:

     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
         name: game-secret
         key: MYSQL_ROOT_PASSWORD

     - name: MYSQL_DATABASE
       value: game

     - name: MYSQL_USER
       valueFrom:
        secretKeyRef:
         name: game-secret
         key: SPRING_DATASOURCE_USERNAME

     - name: MYSQL_PASSWORD
       valueFrom:
        secretKeyRef:
         name: game-secret
         key: SPRING_DATASOURCE_PASSWORD

     ports:

     - containerPort: 3306

     volumeMounts:

     - name: mysql-storage
       mountPath: /var/lib/mysql

     - name: init-script
       mountPath: /docker-entrypoint-initdb.d

   volumes:

   - name: init-script
     configMap:
       name: mysql-init-script

 volumeClaimTemplates:

 - metadata:
     name: mysql-storage

   spec:

     accessModes:

     - ReadWriteOnce

     storageClassName: standard

     resources:

       requests:

         storage: 3Gi

---

apiVersion: v1
kind: Service

metadata:
 name: mysql-svc

spec:

 clusterIP: None

 selector:
   app: mysql

 ports:

 - port: 3306
