apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: kondareddy45/crashloopbackoff-db:v1 
          ports:
            - containerPort: 3306
          env:
            # You will replace these using Secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}

---

apiVersion: v1 
kind: Service
metadata:
  name: "db-svc"
spec:
  type: ClusterIP
  selector:
     app: mysql
  ports:
    - port: 3306
      targetPort: 3306
